### PR TITLE
Updates dependencies versions to work with Python3.9

### PR DESCRIPTION
**Pull request by astivi**

### CODE REVIEW

**Review by diogoaihara — APPROVED** [review]

**Comment by astivi** [comment]
!!! Do not merge until GCP Dataflow has support for apache-beam 2.31 !!!

**Comment by mloonrach** [comment]
https://github.com/google/megalista/pull/35#issue-956714732

**Comment by martinacocco** [comment]
Hi, does Megalista work with Python 3.9 now?

**Comment by caiotomazelli** [comment]
Closing this one as this issue was fixed by #66.

To be clear: Megalista now works with Python 3.9 (answering @martinacocco questions).

**Pull request closed without merging**
