### PR TITLE
Add partial failure support for Google Ads

### PR DESCRIPTION
**Pull request by nivaldoh**
Hi, we've added support for partial failures in Google Ads conversion uploads. By default, if a single row contains errors, the entire batch is blocked. This change aims to allow any valid rows to be uploaded, regardless of errors in other rows in the same batch. For more information: https://developers.google.com/adwords/api/docs/guides/partial-failure

Topics for future consideration:
1. We could make this optional, if needed.
2. Megalist currently shows only the amount of rows that reached the uploader. We intend to contribute again soon with changes that display the number of rows that were, in fact, accepted by the API, as well as logs that register invalid rows individually and the reason for their rejections.

### CODE REVIEW

**Comment by nivaldoh** [comment]
@googlebot I signed it!

**Comment by nivaldoh** [comment]
@googlebot I fixed it.

**Comment by caiotomazelli** [comment]
Hey @antoniolmm and @astivi, can you please advise if enabling partial failure by default can cause any unexpected behaviors downstream?

**Comment by caiotomazelli** [comment]
Hi @nivaldoh, thanks for bearing with us.

I chatted with @antoniolmm and @astivi offline and there are two points blocking this change right now:

1) This setting would affect the Offline Conversions uploader only, as SSD and Customer Match do not accept the partial_failures field. In that case, to avoid confusion, it would be best to activate it for the google_ads_offline_conversions_uploader only to avoid confusion.

2) As of now, we do not check which entries were correctly uploaded on the ofline_conversions_uploader. That means that if we enable partial_failures, the failing entries would fail silently. Could you please add this treatment before proceeding? You can maybe take inspiration from the way errors are treated on the [cm_conversion_uploader](https://github.com/google/megalista/blob/28834a7d38a1b9b800aca159e97c51118c752c72/megalist_dataflow/uploaders/campaign_manager/campaign_manager_conversion_uploader.py#L122-L132).

Can you please take a look and let us know if that makes sense?

**Comment by nivaldoh** [comment]
Hi, sorry for the late reply. It makes perfect sense, and now that #12 is ready, I'll get back to this one and provide an update soon.

**Comment by nivaldoh** [comment]
I am closing this PR as it is now obsolete after the Google Ads API update.

**Pull request closed without merging**
